library(BiocManager)
library(devtools)
library(shiny)
library(svDialogs)
library(lme4)
library(TMB)
library(ggplot2)
library(plyr)
library(zCompositions)
library(lattice)
library(igraph)
library(reshape2)
library(vegan)
library(knitr)
library(tidyverse)
library(haven)
library(dplyr)
library(OTUtable)
library(data.table)
library(ape)
library(microbiome)
library(ggpubr)
library(ggforce)
library(ggplus)
library(nnet)
library(digest)
library(miLineage)
library(HMP)
library(doParallel)
library(DT)
library(coin)
library(exactRankTests)
library(foreach)
library(foreign)
library(Rcpp)
library(qwraps2)
library(magrittr)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(snakecase)
library(stringr)
library(phyloseq)
library(dada2)
library(phangorn)
library(edgeR)
library(limma)
library(DESeq2)
library(metagenomeSeq)
library(DECIPHER)
library(DirichletMultinomial)
library(cgwtools)

# pkg=c ("zCompositions" , "lattice" , "igraph" , "reshape2" ,"vegan",
#        "knitr","tidyverse","foreign","plyr","dplyr","OTUtable","data.table","ape","microbiome",
#        "ggpubr","ggforce","ggplus","nnet","digest","miLineage","HMP","doParallel","DT",
#        "exactRankTests","foreach","Rcpp","shiny","qwraps2","magrittr",
#        "sjPlot","sjmisc","sjlabelled","snakecase","stringr","phyloseq","dada2",
#        "phangorn", "edgeR", "limma","DESeq2", "metagenomeSeq","DECIPHER",
#        "DirichletMultinomial","coin")
# for (i in pkg) {
#   library(i,character.only = TRUE)
# }